/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_com_cj_constom_jnitest_JNITest */

#ifndef _Included_jni_com_cj_constom_jnitest_JNITest
#define _Included_jni_com_cj_constom_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_com_cj_constom_jnitest_JNITest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_com_cj_constom_jnitest_JNITest_getName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
